[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:play]
command=/shobdo-app/bin/shobdo-app -Dplay.crypto.secret=testtahsin -Dhttp.port=9000
directory=/shobdo-app
environment=LOG4J_FORMAT_MSG_NO_LOOKUPS="true"
autostart=true
autorestart=true
startretries=3
startsecs=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=3
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
